### ISSUE TITLE
Wat 1

### ISSUE THREAD

**Issue by benediktvaldez** [benediktvaldez/foooo#1]
Lorem ipsum

**Comment by benediktvaldez** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yTvR7MsC&#x2F;1-eitthva"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Eitthvað</a>

**Comment by benediktvaldez** [comment]
![Goodbye!](http://vignette2.wikia.nocookie.net/glee/images/1/17/Bye_daniel.gif)

**Comment by borgar** [comment]
Mr. commenty man.
